# Generated by Django 4.1.4 on 2023-01-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_categorydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
