# Generated by Django 4.1.5 on 2023-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_categorydb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Price', models.CharField(blank=True, max_length=30, null=True)),
                ('Discription', models.CharField(blank=True, max_length=30, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, max_length=30, null=True, upload_to='')),
            ],
        ),
    ]
