# Generated by Django 3.2.10 on 2023-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='CATEGORY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
