# Generated by Django 4.1.4 on 2023-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_productdb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Image2',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Image3',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to=''),
        ),
    ]
