# Generated by Django 4.1.4 on 2023-02-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
